name: Release

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  release-doc:
    name: release-doc

    strategy:
      matrix:
        #        runs-on: [ubuntu-latest, macOS-latest]
        runs-on: [ubuntu-latest]
      fail-fast: false

    runs-on: ${{ matrix.runs-on }}
    
    steps:
      - uses: actions/checkout@v2
      - run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*
      - run: |
          git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*
      - run: |
          git fetch --prune --unshallow

      - name: Install SSH Client 🔑
        uses: webfactory/ssh-agent@v0.2.0
        with:
          ssh-private-key: |
            ${{ secrets.GH_PAGES_PY_KEY }}
            ${{ secrets.GH_PAGES_KEY }}

      - name: Cache pip Linux
        uses: actions/cache@v1
        if: startsWith(runner.os, 'Linux')
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Cache pip macOS
        uses: actions/cache@v1
        if: startsWith(runner.os, 'macOS')
        with:
          path: ~/Library/Caches/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install Dependencies
        run: ./install_dependencies.sh

      - name: Create Build Environment
        # Some projects don't allow in-source building, so create a separate build directory
        # We'll use this as our working directory for all subsequent commands
        run: cmake -E make_directory ${{runner.workspace}}/build

      - name: Cache CCache
        uses: actions/cache@v1
        with:
          path: ~/.ccache
          #        key: ${{ runner.OS }}-build-ccache-${{ hashFiles('**/package-lock.json') }}
          key: ${{ runner.OS }}-build-ccache
          restore-keys: |
            ${{ runner.OS }}-build-ccache-${{ env.cache-name }}-
            ${{ runner.OS }}-build-ccache-

      - name: Configure CMake
        if: startsWith(runner.os, 'Linux')
        # Use a bash shell so we can use the same syntax for environment variable
        # access regardless of the host operating system
        shell: bash
        # Note the current convention is to use the -S and -B options here to specify source
        # and build directories, but this is only available with CMake 3.13 and higher.
        # The CMake binaries on the Github Actions machines are (as of this writing) 3.12
        run: |
          mkdir -p build
          cd build
          pwd
          ls $GITHUB_WORKSPACE
          $GITHUB_WORKSPACE/tools/genversion.py $GITHUB_WORKSPACE
          cmake -G Ninja $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DBUILD_ALL_PLUGINS=ON -DBUILD_TESTS=ON -DBUILD_COVERAGE=ON -DWITH_GUI=ON -DBUILD_DOCUMENTATION=ON -DPACKAGE_DEB=OFF -DCMAKE_INSTALL_PREFIX=/usr/
        env:
          HAL_BASE_PATH: ${{runner.workspace}}/hal/build

      - name: Build Doxygen
        if: startsWith(runner.os, 'Linux')
        shell: bash
        # Execute the build.  You can specify a specific target with "--target <NAME>"
        run: |
          cd build
          cmake --build . --target doc --clean-first --config $BUILD_TYPE
        env:
          HAL_BASE_PATH: ${{runner.workspace}}/hal/build

      - name: Deploy Doxygen
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          REPOSITORY_NAME: emsec/hal-doc
          ACCESS_TOKEN: ${{ secrets.GH_PAGES_TOKEN}}
          BRANCH: master
          FOLDER: build/documentation/documentation/html
          GIT_CONFIG_NAME: 'github-actions[bot]'
          GIT_CONFIG_EMAIL: 'github-actions[bot]@users.noreply.github.com'

      - name: Build Sphinx
        if: startsWith(runner.os, 'Linux')
        shell: bash
        # Execute the build.  You can specify a specific target with "--target <NAME>"
        run: |
          cd build
          cmake --build . --target hal_py_docs --clean-first --config $BUILD_TYPE
        env:
          HAL_BASE_PATH: ${{runner.workspace}}/hal/build


      - name: Deploy Sphinx
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          REPOSITORY_NAME: emsec/hal-pydoc
          ACCESS_TOKEN: ${{ secrets.GH_PAGES_TOKEN}}
          BRANCH: master
          FOLDER: build/python-doc/html
          GIT_CONFIG_NAME: 'github-actions[bot]'
          GIT_CONFIG_EMAIL: 'github-actions[bot]@users.noreply.github.com'

